#include <stdint.h>
#include <stddef.h>
// C generated by v0.1.3 of the Wlang compiler

int printf(const char* fmt, ...);

int main(int argc, char** argv) {
  printf("Hello, world!\n");
  return 0;
}
