#include <stdint.h>
#include <stddef.h>
// C generated by v0.1.4-wip.1 of the Wlang compiler

const void print_message(const char *const message);

  #include <stdio.h>
  void print_message(const char *const message) {
    printf("%s\n", message);
  }

int main(int argc, char** argv) {
  print_message("Hello, world!");
  return 0;
}
